create table if not exists users
(
    id         integer generated by default as identity
        primary key,
    first_name varchar(100) not null,
    last_name  varchar(100) not null,
    gender     varchar(10)  not null,
    contact    varchar(13)  not null,
    address    varchar(255) not null,
    email      varchar(255) not null,
    doc_type   varchar(20)  not null,
    doc_number varchar(20)  not null,
    password   varchar(20)  not null,
    status     varchar(10)  not null
);

create table if not exists books
(
    id              integer generated by default as identity
        primary key,
    title           varchar(255)      not null,
    authors         varchar(255)      not null,
    publisher       varchar(100)      not null,
    year_of_publish integer           not null,
    number_of_pages integer           not null,
    isbn            varchar(13)       not null
        unique,
    type            varchar(20)       not null,
    sub_type        varchar(20),
    synopse         varchar(255)      not null,
    language        varchar(50)       not null,
    qty             integer           not null,
    available       boolean           not null,
    rating          integer default 0 not null,
    imageUrl        text              not null
);

create table if not exists books_loaned
(
    id          integer generated by default as identity
        primary key,
    user_id     integer           not null
        references users,
    book_id     integer           not null
        references books,
    loan_date   timestamp         not null,
    return_date timestamp         not null,
    status      varchar(20)       not null,
    comments    text              not null,
    rating      integer default 0 not null
);

create table if not exists bookings
(
    id      integer generated by default as identity
        primary key,
    user_id integer     not null
        references users,
    book_id integer     not null
        references books,
    status  varchar(10) not null
);

create table if not exists bookmark
(
    id     integer generated by default as identity
        primary key,
    userid integer not null
        references users,
    bookid integer not null
        references books
);


create view userbookmark
            (id, title, authors, publisher, year_of_publish, number_of_pages, isbn, type, sub_type, synopse, language,
             qty, available, rating, userid)
as
SELECT b.id,
       b.title,
       b.authors,
       b.publisher,
       b.year_of_publish,
       b.number_of_pages,
       b.isbn,
       b.type,
       b.sub_type,
       b.synopse,
       b.language,
       b.qty,
       b.available,
       b.rating,
       bm.userid
FROM books b
         JOIN bookmark bm ON b.id = bm.bookid;


create view bookswithloan (bookid, booktitle, booktype, userid, comment, loandate, returndate, loanstatus) as
SELECT b.id           AS bookid,
       b.title        AS booktitle,
       b.type         AS booktype,
       bl.user_id     AS userid,
       bl.comments    AS comment,
       bl.loan_date   AS loandate,
       bl.return_date AS returndate,
       bl.status      AS loanstatus
FROM books b
         JOIN books_loaned bl ON b.id = bl.book_id;